apiVersion: v1
kind: Namespace
metadata:
  name: leenet
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: leenet
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container
    