imagePullSecrets:
  - name: leenet-registry
image:
  repository: neon-registry.18e7-091a-7bb4-d81e.neoncluster.io/leenet/temporal-adventure-bot
temporalAddress: temporaltest-frontend-headless.temporal.svc.cluster.local
couchbaseEndpoint: my-couchbase.couchbase.svc.cluster.local
