apiVersion: couchbase.com/v2
kind: CouchbaseBackupRestore
metadata:
  name: my-restore
spec:
  repo: my-couchbase-2022-10-23T04_56_39
  backup: my-backup
  start:
    str: latest
  end:
    str: latest