apiVersion: couchbase.com/v2
kind: CouchbaseBackupRestore
metadata:
  name: my-restore
spec:
  repo: #my-couchbase-2022-08-21T10_00_06
  backup: my-backup
  start:
    str: latest
  end:
    str: latest