kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: openebs-jiva-couchbase
provisioner: jiva.csi.openebs.io
parameters:
  cas-type: jiva
  policy: openebs-jiva-default-policy
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
